### ISSUE TITLE
Enhancement - Game numbers don't continuously increment

### ISSUE THREAD

**Issue by MadnessExpress** [z64/discord-against-humanity#22]
Someone pointed out that it would be better to not continually increment the number of the game room. That way every time you start a fresh game it starts at room game_1 or increments if game_1 already exists.

**Comment by z64** [comment]
I have done this purposely as the game number matches its internal ID, which is important for capturing bug reports and such. I will consider changing it to something like you described, but for now and the foreseeable future I would like it to stay as it is. 

Besides, what's in a name? :wink:
